name: fun_education_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: 
  cupertino_icons: null
  dio: null
  flutter:
    sdk: flutter
  flutter_svg: 
  get:
  google_fonts: null
  image_picker: null
  pinput: null
  shared_preferences: null
  timeline_tile:
  intl: null
  fl_chart: 
  easy_date_timeline: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
