name: fun_education_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: null
  dio: null
  flutter:
    sdk: flutter
  flutter_svg: null
  get: null
  google_fonts: null
  image_picker: null
  persistent_bottom_nav_bar: null
  pinput: null
  shared_preferences: null
  timeline_tile:
  intl: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
