// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fWHn-hD0x3AlWxQUeHll85Xv2EPR0ik',
    appId: '1:145778819833:web:a4bd50982394171c5ed828',
    messagingSenderId: '145778819833',
    projectId: 'fun-education-app',
    authDomain: 'fun-education-app.firebaseapp.com',
    storageBucket: 'fun-education-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABjmA_s5kCEWxCttjTZHF37VOiZT-8Ffc',
    appId: '1:145778819833:android:04b11ca797ea42615ed828',
    messagingSenderId: '145778819833',
    projectId: 'fun-education-app',
    storageBucket: 'fun-education-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xiAgBls9l5mTN7B0Kqq-EzP6c2dIWNU',
    appId: '1:145778819833:ios:1007eded8e0d9b285ed828',
    messagingSenderId: '145778819833',
    projectId: 'fun-education-app',
    storageBucket: 'fun-education-app.appspot.com',
    iosBundleId: 'com.example.funEducationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xiAgBls9l5mTN7B0Kqq-EzP6c2dIWNU',
    appId: '1:145778819833:ios:786b314bfacff35f5ed828',
    messagingSenderId: '145778819833',
    projectId: 'fun-education-app',
    storageBucket: 'fun-education-app.appspot.com',
    iosBundleId: 'com.example.funEducationApp.RunnerTests',
  );
}
